# 商店索引，不可重复
default_sellshop:

  # 商店类型：sell(售卖商店)、buy(收购商店)
  type: 'sell'

  # 商店场景：personal(个人商店)、server(全服商店)
  # 个人商店：每个玩家的刷出的商店商品，以及商品价格和商品限购次数均不一致。
  # 全服商店，每个玩家看到的商店是同一个，每个人的限购次数一致，全服限购次数共享。
  scene: 'personal'

  # 刷新设置
  refresh:
    # 类型，有timely、daily、weekly和monthly四种
    # 当为timely时，time则是计时而不是时间点
    # 例如timely类型下，
    # 当time为'2:00:00'代表每隔2小时刷新一次
    # 当time为'0:30:00'代表每隔30分钟刷新一次
    # 以1970年1月1日00:00:00为间隔起点
    # 当为weekly时，需要写为'weekly:1'，代表每周一
    # 'weekly:1,2,5,6'代表每周一、二、五、六刷新，允许写1~7，写错需要报错提示
    # 当为monthly时，需要写为'monthly:1'，代表每个月第一天
    # 'monthly:1,2,5,30'代表每个月的第一、二、五、三十天刷新，允许写1~31，写错需要报错提示
    # 像写30的情况下，二月会无法生效，因为二月只有27或28天
    type: 'daily'
    # 刷新时间点（时:分:秒）
    time: '17:00:00'

  # 消息，提示全服所有玩家
  # 不写默认为无聊天栏文本提示
  message:
    # 商店刷新提示
    restock: '商店进货了！'
    # 商店刷新，但是没有随机到任何一个商品时的提示
    noshops: '我被打劫了，无法卖货'

  # 音效
  # 不写默认为无音效
  sound:
    # 打开商店的音效
    open_shop: null
    # 购买/售出成功音效
    success: 'entity.villager.yes'
    # 购买/售出失败音效
    fail: 'entity.villager.no'

  # 商店标题
  # %page%与%page_all%为配置内置占位符
  # %page%为当前页
  # %page_all%为该商店最大页数
  title: 'default_shop [%page%/%page_all%]'

  # 商店布局（参考trmenu插件）
  # 展示界面与售卖界面相同
  # 列数应为0~9列，少于9列的情况，补空至9列。
  # 行数应为1~6行，
  layout:
  - 'xxxx@xxxx'
  - 'xooooooox'
  - 'xooooooox'
  - 'xooooooox'
  - 'xooooooox'
  - 'x<xx!xx>x'

  icons:
    'x':
      # 常规展示物品，type有item、shops、previous_page、next_page、sort四种
      type: item
      # 物品信息（type为shops时不写）
      display:
        # 物品原型
        material: 'paper'
        # 物品数据（方便染色）
        data: 0
        # 物品数量（不写默认为1）
        amount: 1
        # 物品名称
        name: '这是边框'
        # 物品lore
        lore:
        - '第一行lore'
        - '第二行lore'
        # 物品nbt
        nbt:
          custommodeldata: 'test'

    
    '!':
      type: item
      display:
        material: 'beacon'
        data: 0
        name: '这是边框'
        amount: 1
        lore:
        - '你当前拥有%xconomy_balance%手艺币'
        nbt:
          custommodeldata: 'money'
 
    'o':
      # 商品槽，点击后执行一次购买或售出操作，为空时不执行
      # 所有o为商品可用区域，随机到的商品会从第一格开始从左往右，从上至下排布
      type: shops

    '<':
      # 上一页键，点击后翻到上一页，若当前为第一页，则翻到最后一页
      type: previous_page
      display:
        material: 'arrow'
        name: '上一页'

    '>':
      # 下一页键，点击后翻到下一页，若当前为最后一页，则翻到第一页
      type: next_page
      display:
        material: 'arrow'
        name: '下一页'

    '@':
      # 排序，默认按照索引数字排序
      # 左键点击后排序如下：
      # 1、索引数字升序
      # 2、出现概率升序（概率相同则按索引排序）
      # 3、售卖/收购价格升序（概率相同则按索引排序）
      # 3、售卖/收购数量升序（概率相同则按索引排序）
      # 右键点击切换当前当前排序类型的升序、降序状态
      type: sort
      display:
        material: 'diamond'
        name: '点击排序'
        lore:
        - '左键排序 索引 / 概率 / 价格 / 数量'
        - '右键切换 升序 / 降序'

  
  shops:
    # 商店商品索引，单个商店内不可重复，必须为数字
    1:
      # 商品物品库来源，当前仅支持zaphkiel
      # 写法'物品库来源:物品库内物品索引'
      id: 'zaphkiel:镇好剑'
      # 随机附魔
      # 设计上，附魔包含冲突和非冲突
      # 因此列表下每个元素下可以设置多个附魔选择
      # enchantments列表类型
      enchantments:
        # 获得该附魔的概率
      - chance: 0.35
        enchant:
          # id为附魔名称
        - id: FIRE_ASPECT
          # 选中该附魔的权重，当enchant字段下只有一种附魔，则100%选中该附魔
          # 在有不止一种附魔的情况下，按照权重进行选择
          # 不写权重则默认权重为1
          weight: 50
          # level为附魔等级，为字典类型
          # 若无该字段默认只有1级附魔，且权重为1，溢价为0
          level_list:
            # 附魔等级
          - level: 1
            # 权重，同上，不写权重默认权重为1
            # 例如该附魔等级总权重为150，而1级权重为50，代表生成该附魔时，有1/3概率为1级
            weight: 50
            # 溢价比，不写默认为0
            # 算法与下方“单价”字段写法一致
            # 例如原价随机到了200，并随机到了1级附魔，溢价比随机到了0.03，那么实际购买价格就变成了206
            # 溢价部分
            premium: 'NL:0.02-0.04'
          - level: 2
            weight: 50
            premium: 'NL:0.03-0.09'
          - level: 3
            weight: 30
            premium: 'NL:0.05-0.25'
          - level: 4
            weight: 10
            premium: 'NL:0.07-0.49'
          - level: 5
            weight: 6
            premium: 'NL:0.09-0.81'
          - level: 6
            weight: 3
            premium: 'NL:0.11-1.21'
          - level: 7
            weight: 1
            premium: 'NL:0.15-2.25'
      # 每个元素也可为列表类型，可以写多种附魔，生成时根据权重，随机选择其中之一
      # 例如这里“锋利”、“亡灵杀手”、“节肢杀手”三个附魔权重为3:1:1
      # 则代表，若该节点被选中，那么出现锋利附魔的概率是60%，其余两个则各为20%。
      - chance: 0.55
        enchant:
        - id: DAMAGE_ALL
          weight: 3
          level_list:
          - level: 2
            weight: 50
            premium: 'NL:0.04-0.09'
          - level: 3
            weight: 20
            premium: 'NL:0.09-0.16'
        - id: DAMAGE_UNDEAD
          weight: 1
          level_list:
          - level: 2
            weight: 50
            premium: 'NL:0.04-0.09'
          - level: 3
            weight: 20
            premium: 'NL:0.09-0.16'
        - id: DAMAGE_ARTHROPODS
          weight: 1
          level_list:
          - level: 2
            weight: 50
            premium: 'NL:0.04-0.09'
          - level: 3
            weight: 20
            premium: 'NL:0.09-0.16'
      # 单价
      # 写法1：'取值算法:平均价格,参数'
      # 写法2：'取值算法:最低价格-最高价格'
      # 写法3：'平均价格,参数'(默认使用U算法)
      # 写法4：'最低价格-最高价格'(默认使用U算法)
      # 写法5: '固定价格'
      # 可用取值算法：U(均匀分布)、N(正态分布)、NL(左半正态分布)、NR(右半正态分布)
      # 对于U、N、NL、NR，参数为拓展区间，例如'U:400,100'，那么价格为300-500
      # 随机到的价格最低值为0.01。
      # 当算法为U时，取到300与400的概率是一致的
      # 当算法为N时，取到400的概率远高于300
      # 当算法为NL时，取到500的概率远高于300和400，即500成了正态分布的均值，值越低概率越低
      # NR算法与NL相反，取到300的概率远高于400和500，即300成了正态分布的均值，值越高概率越低
      # 允许出现小数，小数点限制两位
      money: 'N:200-800'
      # 单次购买物品数量
      # 写法同价格
      amount: '1'
      # 限购数量，-1代表不限购
      # 写法同价格
      # 只可能出现整数
      # 商店类型为personal时，limit_server无效，不会读取
      limit_personal: '1-2'
      limit_server: 'U:88,11'
      # 刷出概率，小数形式，1=100%
      # 不写默认为100%
      chance: 0.15
      # 购买相关机制
      # 玩家需要花money*amount的价格，才能完成一次购买。
      # 例如amount随机到了5，money为100-200，那么5件物品的价格区间则变为500-1000，从这个区间内进行取值
      # 例如取到了666，玩家左键需要花666，才能买到5个商品，才能完成一次购买
      # 限购是对于交易次数而言的，例如10次限购机会，玩家1次完成了上述交易，买到5个物品，实际上只消耗1次限购机会，而非5次。


        
